# 日志输出到控制台
appender=com.p6spy.engine.spy.appender.Slf4JLogger
# 慢 SQL 阈值（ms）
executionThreshold=1000
# 慢 SQL 才输出（仅输出慢sql）
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=|executionTime=%(executionTime)ms|sql=%(sqlSingleLine)
# 日志级别
logLevel=info
